### ISSUE TITLE
Callouts Showing Up Weird

### ISSUE THREAD

**Issue by SumitNalavade** [Reveille-Rides/ReveilleRides#105]
<img width="483" alt="Screenshot 2024-01-25 at 11 28 09 AM" src="https://github.com/Reveille-Rides/ReveilleRides/assets/48499839/be1c1ca2-9e03-4f88-8415-728fb2baa438">

**Comment by bwees** [comment]
Any headway on this?

**Comment by bwees** [comment]
fixed by #125
