### ISSUE TITLE
Allow user to tap a "Other" route on timetable view and it will select the other route and open RouteDetail

### ISSUE THREAD

**Issue by bwees** [Reveille-Rides/ReveilleRides#120]
<img width="369" alt="Screenshot 2024-02-03 at 11 58 32 AM" src="https://github.com/Reveille-Rides/ReveilleRides/assets/12686250/df82e0d5-79d6-435d-b286-d21c9bf512c9">

I believe you should be able to just set the selected route and dismiss the timetable sheet since the routeDetail is already below it.

**Comment by bwees** [comment]
<img width="302" alt="Screenshot 2024-02-03 at 12 00 28 PM" src="https://github.com/Reveille-Rides/ReveilleRides/assets/12686250/c9e57030-c737-4d1c-899c-47d8fc95db84">

make it so only this is touchable, dont make the actual timetable touchable

**Comment by Eli410** [comment]
Strange bug while attempt to implement this, the main sheet opens itself up when the detail route sheet is still present, causing two sheets to be opened at the same time, so I gave up.

**Comment by bwees** [comment]
> Strange bug while attempt to implement this, the main sheet opens itself up when the detail route sheet is still present, causing two sheets to be opened at the same time, so I gave up.

Can you send a link to your branch so I can try to debug?

**Comment by Eli410** [comment]
I deleted the changes 😭 But its not a lot I can try the same thing later today and send you it.

**Comment by bwees** [comment]
No worries, I will take a crack at it by myself. Don't worry about redoing all the changes.

**Comment by bwees** [comment]
is this a similar point that you got to @Eli410 ?

https://github.com/Reveille-Rides/ReveilleRides/tree/bwees/select-route-from-timetable

**Comment by Eli410** [comment]
Yep, same bug

**Comment by bwees** [comment]
nice, lets put this feature on hold for now and we can revisit
