### ISSUE TITLE
Image loading for the new bus icons is super slow.

### ISSUE THREAD

**Issue by bwees** [Reveille-Rides/ReveilleRides#13]
When I change tabs on the bottom drawer, the images take a considerable time to load. What if we change it so that instead of loading the icons as images, we create a small view of 50x50px with the background color and text for the icon? This will save on app size (don't need to ship a ton of static images) and allow us to dynamically update routes once we integrate API. I can also take this on if needed

**Comment by SumitNalavade** [comment]
I agree, this would definitely save on app size and feel more responsive

**Comment by bwees** [comment]
Working on PR right now!

**Comment by bwees** [comment]
See #15

**Comment by SumitNalavade** [comment]
Completed in #15
