### ISSUE TITLE
Add a time bubble on all stop callout that shows when is the next buses

### ISSUE THREAD

**Issue by Eli410** [Reveille-Rides/ReveilleRides#130]
## Current stop callout:
![Untitled drawing (1)](https://github.com/Reveille-Rides/ReveilleRides/assets/68358276/c50e484f-0013-4b89-8570-8aeb247c3bd1)
Add the bubble that shows when the next bus will be at that stop

## After changes:
![Untitled drawing](https://github.com/Reveille-Rides/ReveilleRides/assets/68358276/3b1a773e-1978-4a95-bc82-16f2f9fe9da4)

Check with UI people for exact UI implementation

**Comment by bwees** [comment]
Also see #131. 1 team will work on both of these issues

**Comment by bwees** [comment]
See https://github.com/Reveille-Rides/ReveilleRides/blob/5149be3c2cb1f8882da89b35e0b116bd0191e028/app/components/ui/StopCell.tsx#L160 for implementation

**Comment by bwees** [comment]
Solved by #154
