### ISSUE TITLE
Add "All" button to stop callout

### ISSUE THREAD

**Issue by Eli410** [Reveille-Rides/ReveilleRides#131]
## Current callout:
![Untitled drawing (2)](https://github.com/Reveille-Rides/ReveilleRides/assets/68358276/6a0e09ff-b939-48cd-8e43-35bfce6ea0a4)

It would be nice to have the "All" button in the route detail sheet which shows the timetable and other routes that goes to this stop on the callout as well.

![Untitled drawing (1)](https://github.com/Reveille-Rides/ReveilleRides/assets/68358276/58d29c4a-ac6f-42e3-b404-57d7bf3fb07f)

## Would look something like this after changes:
![Untitled drawing](https://github.com/Reveille-Rides/ReveilleRides/assets/68358276/12337f52-4e88-4e4e-bc99-69a93b7a1e7c)

Talk to UI people for the exact UI implementation.

**Comment by bwees** [comment]
Not sure if we can add buttons in callouts but I will look more into it

**Comment by bwees** [comment]
Not dealing with buttons in callouts rn
