### ISSUE TITLE
Stop Callouts

### ISSUE THREAD

**Issue by shweta-kumaran** [Reveille-Rides/ReveilleRides#33]
Please work on StopCallout.tsx which is under app/components/callouts

A general framework is provided. Please center and adjust the callout to look like this. Please keep in mind that we want to be able to adjust the size based on the length of the text so maybe use something like flex. Good luck! 
<img width="381" alt="Screenshot 2023-11-07 at 9 49 54 PM" src="https://github.com/pavitgopal/ReveilleRides/assets/89658334/0b21f5b0-9974-4d16-a0a6-5c0a342c1c1c">

**Comment by bwees** [comment]
This can be closed!
