### ISSUE TITLE
Bus Callouts

### ISSUE THREAD

**Issue by shweta-kumaran** [Reveille-Rides/ReveilleRides#34]
Please work on BusCallout.tsx which is under app/components/callouts

A general framework is provided. Please center and adjust the callout to look like this. Please keep in mind that we want to be able to adjust the size based on the length of the text so maybe use something like flex. Good luck![image](https://github.com/pavitgopal/ReveilleRides/assets/89658334/52f13c2c-0e77-4ce0-b637-4d107b9aea5e)

**Comment by bwees** [comment]
This can also be closed!
