### ISSUE TITLE
Replace Dropdown Select With Horizontal Checkboxes For On Campus/Off Campus

### ISSUE THREAD

**Issue by SumitNalavade** [Reveille-Rides/ReveilleRides#6]
On the bottom drawer component, replace the current dropdown select with a set of horizontal checkboxes to toggle between on-campus/off-campus routes.

Currently, we have a dropdown select on the bottom drawer:
<img width="367" alt="Screenshot 2023-10-23 at 1 10 53 AM" src="https://github.com/pavitgopal/ReveilleRides/assets/48499839/79aa920b-bb8f-41a2-beb6-8a6f920069f9">

We should transition over to a set of horizontal checkboxes to make the UI clearer and reduce redundancy:
<img width="345" alt="Screenshot 2023-10-23 at 1 12 19 AM" src="https://github.com/pavitgopal/ReveilleRides/assets/48499839/cd922989-4056-4217-b482-b7100606f579">

Currently, we're using a third-party dependency, ```react-native-dropdown-picker``` to implement the dropdown select. You should remove the dependency entirely and try to implement the checkboxes using native components. 

In addition, you should keep track of the state of what routes are selected and render only those that are selected.

Right now, we are keeping track of the state of the dropdown:
```
 const [value, setValue] = useState('onCampus');
    const [items, setItems] = useState([
        { label: 'On Campus', value: 'onCampus' },
        { label: 'Off Campus', value: 'offCampus' },
        { label: 'All', value: 'all' }
    ]);

<StyledDropDownPicker
    open={open}
     value={value}
     items={items}
     setOpen={setOpen}
     setValue={setValue}
     setItems={setItems}
     dropDownDirection="BOTTOM"
     className="border border-gray-200"
     showArrowIcon={false}
     placeholder="On Campus"
     dropDownContainerStyle={{ borderColor: 'lightgray' }}
/>

<FlatList
                    data={(value === 'onCampus') ? busRoutes.filter(route => route.onCampus) : ((value === 'offCampus') ? busRoutes.filter((route) => !route.onCampus) : busRoutes)}
                    renderItem={({ item: busRoute }) => {
                        return (
                            <View className="my-3">
                                <Text className='text-lg font-bold text-neutral-900'>{busRoute.name}</Text>
                            </View>
                        )
                    }}
                    keyExtractor={busRoute => busRoute.id}
                />
```

The data attribute has a nested ternary which renders only on-campus routes if the value of the dropdown is 'onCampus' by filtering the list of all bus routes, renders only off-campus routes if the value of the dropdown is 'offCampus' if the value of the dropdown is 'offCampus' and renders the entire list of bus routes if none of the other ternary statements are matched.

Please leave a comment saying you want to be assigned to the issue and open a pull request for code review!

**Comment by bwees** [comment]
I will take this, Kayley and I were working on a good UI for this. Will determine the best method once we meet this Friday.

**Comment by SumitNalavade** [comment]
> I will take this, Kayley and I were working on a good UI for this. Will determine the best method once we meet this Friday.

Have at it!

**Comment by SumitNalavade** [comment]
Completed in #14
