### ISSUE TITLE
Add button to recenter map on user's location

### ISSUE THREAD

**Issue by SumitNalavade** [Reveille-Rides/ReveilleRides#7]
Add a button ontop of the map view to recenter the map on the current location of the user.

Currently, we do not have anything that would recenter the map:
<img width="382" alt="Screenshot 2023-10-23 at 1 20 54 AM" src="https://github.com/pavitgopal/ReveilleRides/assets/48499839/cc024fb2-630f-463f-8eb3-7a271c666f63">

Some sort of icon with styling to recenter the map would look something like this:
<img width="293" alt="Screenshot 2023-10-23 at 1 22 22 AM" src="https://github.com/pavitgopal/ReveilleRides/assets/48499839/64d1f00d-220c-4b7c-a6e9-506e8e8efd47">

You can extract the functionality out of the useEffect block into a separate function, but make sure to call it in the useEffect function as well:
```
useEffect(() => {
        (async () => {
            let { status } = await Location.requestForegroundPermissionsAsync();
            if (status !== 'granted') {
                return;
            }

            let location = await Location.getCurrentPositionAsync({
                accuracy: Location.Accuracy.Balanced,
                timeInterval: 2
            });

            setLocation({ latitude: location.coords.latitude, longitude: location.coords.longitude, latitudeDelta: 0.019075511625736397, longitudeDelta: 0.011273115836317515 });
        })();
    }, []);
```
This code requests permission to use the users location while the app is open and if it is granted, sets the latitude and longitude in a state variable.

The latitude/longitude are then passed into a MapView component in the region attribute as such:
```
 <StyledMapView 
            showsUserLocation={true}
            region={location}
            className='w-full h-full' />
```

Please leave a comment saying you want to be assigned to the issue and open a pull request for code review!

**Comment by bwees** [comment]
I will do this!

**Comment by SumitNalavade** [comment]
> I will do this!

Go for it!

**Comment by bwees** [comment]
How do you want me to handle icons? I was gonna add one to recenter like the iOS one.

I can add the react native vector icons library in this pr if you would like

**Comment by SumitNalavade** [comment]
> react native vector icons

Sounds good, we'll probably need an icon library in the future anyway

**Comment by bwees** [comment]
See #8

**Comment by bwees** [comment]
![image](https://github.com/pavitgopal/ReveilleRides/assets/12686250/7730dc83-8a8c-4349-b762-1f0a505d7d1c)

**Comment by bwees** [comment]
I dont think there is a reason to show a profile icon since we are not going to have a server component at this time and it is also a similar UI to other map apps.

**Comment by SumitNalavade** [comment]
> I dont think there is a reason to show a profile icon since we are not going to have a server component at this time and it is also a similar UI to other map apps.

I agree I like what you have right now. Give me some time I'll do a code review.

**Comment by SumitNalavade** [comment]
Completed in #8
